test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,7 +18,7 @@ jobs:
     - name: Check dist directory
       run: ls dist/
     
-    - name: Run test 1
+    - name: Run test 0
       run: |
         output=$(node dist/test.js)
         exist_code=$output
@@ -27,6 +27,13 @@ jobs:
         echo "Error: The Node.js script failed with exit code $exit_code"
         exit 1
         fi
-    - name: Run Test 2
+    - name: Run Test 1
       run: |
+        output=$(node dist/test1.js)
+        exist_code=$output
+
+        if [ $exit_code -ne 0 ]; then
+        echo "Error: The Node.js script failed with exit code $exit_code"
+        exit 1
+        fi
       
