test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,23 +27,23 @@ jobs:
         echo "Error: The Node.js script failed with exit code $exit_code"
         exit 1
         fi
-    - name: Run Test 1
-      run: |
-        output=$(node dist/test1.js)
-        exist_code=$output
+    # - name: Run Test 1
+    #   run: |
+    #     output=$(node dist/test1.js)
+    #     exist_code=$output
 
-        if [ $exit_code -en 0 ]; then
-        echo "Error: The Node.js script failed with exit code $exit_code"
-        exit 1
-        fi
-    - name: Run Test 2
-      run: |
-        output=$(node dist/test2.js)
-        exit_code=$output
+    #     if [ $exit_code -en 0 ]; then
+    #     echo "Error: The Node.js script failed with exit code $exit_code"
+    #     exit 1
+    #     fi
+    # - name: Run Test 2
+    #   run: |
+    #     output=$(node dist/test2.js)
+    #     exit_code=$output
 
-        if [ $exit_code -ne 0 ]; then
-        echo "Error: The Node.js script failed with exit code $exit_code"
-        exit 1
-        fi
+    #     if [ $exit_code -ne 0 ]; then
+    #     echo "Error: The Node.js script failed with exit code $exit_code"
+    #     exit 1
+    #     fi
         
 
