Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,4 +13,14 @@ jobs:
         node-version: '18'
 
     - name: Install dependencies
-      run: npm install    
+      run: npm install
+    
+    - name: Run test
+      run: |
+        output=$(node dist/test.js)
+        exist_code=$output
+
+        if [ $exit_code -ne 0 ]; then
+        echo "Error: The Node.js script failed with exit code $exit_code"
+        exit 1
+        fi
